# General configuration
logging:
  level: WARNING
  logfile: "log/opendataharvest.log"

paths:
  crosswalk: "data/crosswalk.csv"
  ogm_path: "tmp/opengeometadata"
  defaultbbox: "data/default_bbox.csv"

requirements:
  check_required:
    - dct_publisher_sm
    - dct_spatial_sm
    - gbl_mdVersion_s
    - dct_title_s
    - id
    - gbl_mdModified_dt
    - gbl_resourceClass_sm

deprecated_fields:
  remove_deprecated:
    - dc_type_s
    - layer_geom_type_s
    - dct_isPartOf_sm
    - uw_supplemental_s
    - uw_notice_s
    - uuid
    - stanford_rights_metadata_s
    - stanford_use_and_reproduction_s
    - stanford_copyright_s

wisco_providers:
  - UW-Madison Robinson Map Library
  - WisconsinView
  - UW Digital Collections Center
  - Wisconsin State Cartographer's Office

string2array_suffixes:
  - sm
  - im

# DCAT Harvester specific configuration
CONFIG:
  CATALOG: "DCAT_Sites" # TestSites, DCAT_Sites, or CKAN_Sites
  OUTPUTDIR: "opendataharvest"
  COLLECTION_RECORD: "data/agsl-opendata-harvest.json"
  DEFAULTBBOX: "data/default_bbox.csv"
  MAXRETRY: 3
  SLEEPTIME: 2
  SCHEMA: "https://raw.githubusercontent.com/UWM-Libraries/GeoDiscovery/main/schema/geoblacklight-schema-aardvark.json"

################
# Localization #
################
DEFAULT:
  MEMBEROF:
    - "agsl-opendata-harvest"
  RESOURCECLASS:
    - "Datasets"
  ACCESSRIGHTS: "Public"
  MDVERSION: "Aardvark"
  LANG:
    - "English"
  PROVIDER: "American Geographical Society Library – UWM Libraries"
  SUPPRESSED: false
  RIGHTS:
    - Although this data is being distributed by the American Geographical Society Library at the University of Wisconsin-Milwaukee Libraries, no warranty expressed or implied is made by the University as to the accuracy of the data and related materials. The act of distribution shall not constitute any such warranty, and no responsibility is assumed by the University in the use of this data, or related materials.
  RESOURCETYPE:
    - "Digital maps"
  FORMAT: None
  DESCRIPTION: This dataset was automatically cataloged from the creator's Open Data Portal. In some cases, publication year and bounding coordinates shown here may be incorrect. Additional download formats may be available on the author's website. Please check the Resource Link for additional information.
  DISPLAYNOTE: 'Info: This dataset was automatically cataloged from the creator''s Open Data Portal. See the Resource Link to view the original resource.'

##############
# Test Sites #
##############
TestSites:
  MilwaukeeCounty_OpenData:
    CreatedBy: "Milwaukee County"
    SiteURL: "https://data-mclio.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "MilwaukeeCounty"
    DefaultBbox: "MilwaukeeCounty"
    SkipList:
      - UUID: "d7f707071cd24b83ab3b9adb8a7d10ce"
      - UUID: "bce9201dd312445b9b4567ee14d8032a"
      - UUID: "84c7b8d95af04cdda6b0c2ae26590531"
      - UUID: "7a1d3d055d4b4457845c721088c132f0"
    Spatial: ["Milwaukee County", "Wisconsin", "United States"]
  DHS_OpenData:
   CreatedBy: "Wisconsin Department of Health Services"
   SiteURL: "https://data.dhsgis.wi.gov/data.json"
   SiteName: "DHS"
   Spatial: ["Wisconsin", "United States"]
   DefaultBbox: "Wisconsin"
   AppList:
    - UUID: "e1ca38bf16f54fb8ac879b386dbce422" # Flood Risk Map
    - UUID: "861fc902539e436ebef7a86a10e9337b" # Immunization Map
    - UUID: "43ed2d88cf1348608230572166d76697" # Radon Map
   SkipList:
    - UUID: "ca921d70bdd84ae8bc84cd09abd822d7" # link to census geography website
    - UUID: "00883495714c42a9be53b76b24300c8e" # GIS data disclaimer
    - UUID: "200036084844418bb3119d963cd7d98c" # OSDP Help?
    - UUID: "29c62b7a834944ef8196573c123d7a9d"

########################
########################
# DCAT compliant sites #
########################
########################
DCAT_Sites:

############################
# Wisconsin State Agencies #
############################
  DHS_OpenData:
   CreatedBy: "Wisconsin Department of Health Services"
   SiteURL: "https://data.dhsgis.wi.gov/data.json"
   SiteName: "DHS"
   Spatial: ["Wisconsin", "United States"]
   DefaultBbox: "Wisconsin"
   AppList:
    - UUID: "e1ca38bf16f54fb8ac879b386dbce422" # Flood Risk Map
    - UUID: "861fc902539e436ebef7a86a10e9337b" # Immunization Map
    - UUID: "43ed2d88cf1348608230572166d76697" # Radon Map
   SkipList:
    - UUID: "ca921d70bdd84ae8bc84cd09abd822d7" # link to census geography website
    - UUID: "00883495714c42a9be53b76b24300c8e" # GIS data disclaimer
    - UUID: "200036084844418bb3119d963cd7d98c" # OSDP Help?
    - UUID: "29c62b7a834944ef8196573c123d7a9d"

  DOT_OpenData:
    CreatedBy: "Wisconsin Department of Transportation"
    SiteURL: "https://data-wisdot.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "DOT"
    Spatial: ["Wisconsin", "United States"]
    DefaultBbox: "Wisconsin"
    AppList:
      - UUID: "e5b648476a8b487b8d778f41fef0936d" # Community Maps
      - UUID: "d1bd22f9e369402d9b665017d77b0125" # Culvert Inventory
    SkipList: ""

  LTSB_OpenData:
    CreatedBy: "Wisconsin Legislative Technology Services Bureau"
    SiteURL: "https://data-ltsb.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WILTSB"
    DefaultBbox: "Wisconsin"
    DatasetPrefix: ""
    Spatial: ["Wisconsin", "United States"]
    DatasetPostfix: ", WI LTSB"
    SkipList: ""

  DNR_OpenData:
    CreatedBy: "Wisconsin Department of Natural Resources"
    SiteURL: "http://data-wi-dnr.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "DNR"
    DefaultBbox: "Wisconsin"
    Spatial: ["Wisconsin", "United States"]
    AppList:
      - UUID: "01e11ad8f08945a88b140f0f40fcf057" # Surface Water Data Viewer
      - UUID: "f34ca451d5d14e23a588e8a93dc9417e" # Wetland Monitoring Gallery
      - UUID: "200c06fc04074ef7ae24c0b74737b187" # Wetland Geodatabase
      - UUID: "4da3c08881cb4bd880bf9f695840b29b" # Land Patents
    SkipList:
      - UUID: "0542ce7130144fe69705848f8d319ae7"
      - UUID: "438c9dbdf5374faeba3339253e0c231c"
      - UUID: "54b132238f8f4510adfe3829e2714f4b"
      - UUID: "9a50a15aa6664da6ab44f0d4f02ffa94"

  WEM_OpenData:
    CreatedBy: "Wisconsin Emergency Management"
    SiteURL: "http://data-wem.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WEM"
    Spatial: ["Wisconsin", "United States"]
    DefaultBbox: "Wisconsin"
    SkipList:
      - UUID: "ef7f2afba9aa4f3fbdbf3ff45c8e6c2a"

  DPI_OpenData:
    CreatedBy: "Wisconsin Department of Public Instruction"
    SiteURL: "https://data-wi-dpi.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "DPI"
    Spatial: ["Wisconsin", "United States"]
    DefaultBbox: "Wisconsin"
    AppList:
      - UUID: "cb7f4bc5117f45fda3d1a54cc4d22747"
    SkipList:
      - UUID: "1ffca2ff7ccf49f8b9a53f3fd4ad8d38"
      - UUID: "56cefe26736947c7825ff5bdc00f593c"
      - UUID: "0688c2e71e7b43f3b74f07d40f903692"

###################
# Municipalities  #
###################
  Fitchburg_OpenData:
    CreatedBy: "City of Fitchburg"
    SiteURL: "https://opendata-fitchburgwi.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "Fitchburg"
    DefaultBbox: "Fitchburg"
    Spatial: ["Fitchburg", "Wisconsin", "United States"]
    SkipList: ""

  Madison_OpenData:
    CreatedBy: "City of Madison"
    SiteURL: "http://data-cityofmadison.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "Madison"
    Spatial: ["Madison", "Wisconsin", "United States"]
    DefaultBbox: "Madison"
    AppList:
      - UUID: "75f8d4d3c2734264af5c37e4387ad611"
      - UUID: "1398a6c1f2f64e2fa21f80d97ffb274e"
    SkipList:
      - UUID: "d2fce75af4e547748f8db0409039de50"

  WisconsinRapids_OpenData:
    CreatedBy: "City of Wisconsin Rapids"
    SiteURL: "http://rapidsdata-wisconsinrapids.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WisconsinRapids"
    DefaultBbox: "WisconsinRapids"
    Spatial: ["Wisconsin Rapids", "Wisconsin", "United States"]
    SkipList: ""

  SunPrairie_OpenData:
    CreatedBy: "City of Sun Prairie"
    SiteURL: "https://maps-sunprairie.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "SunPrairie"
    DefaultBbox: "Sun Prairie"
    Spatial: ["Sun Prairie", "Wisconsin", "United States"]
    SkipList: ""

########################
# Regional Planning Comm's #
########################
  CARPC_OpenData:
    CreatedBy: "Capital Area Regional Planning Commission"
    SiteURL: "https://data-carpc.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "CARPC"
    DefaultBbox: "Wisconsin"
    Spatial: ["Wisconsin", "United States"]
    SkipList: ""

  ECWRPC_OpenData:
    CreatedBy: "East Central Wisconsin Regional Planning Commission"
    SiteURL: "http://data-ecwrpc.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "ECWRPC"
    Spatial: ["Wisconsin", "United States"]
    DefaultBbox: "Wisconsin"
    SkipList: ""

#################
# Counties      #
#################
  AshlandCounty_OpenData:
    CreatedBy: "Ashland County"
    SiteURL: "https://data-ashlandcountywi.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "AshlandCounty"
    Spatial: ["Ashland County", "Wisconsin", "United States"]
    DefaultBbox: "Ashland"
    SkipList: ""

  ColumbiaCounty_OpenData:
    CreatedBy: "Columbia County"
    SiteURL: "http://opendata-cclid.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "ColumbiaCounty"
    Spatial: ["Columbia County", "Wisconsin", "United States"]
    DefaultBbox: "Columbia"
    SkipList: ""

  DaneCounty_OpenData:
    CreatedBy: "Dane County"
    SiteURL: "https://gis-countyofdane.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "DaneCounty"
    Spatial: ["Dane County", "Wisconsin", "United States"]
    DefaultBbox: "Dane"
    SkipList: ""

  EauClaireCounty_OpenData:
    CreatedBy: "Eau Claire County"
    SiteURL: "https://hub-eccounty.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "EauClaireCounty"
    Spatial: ["Eau Claire County", "Wisconsin", "United States"]
    DefaultBbox: "EauClaire"
    SkipList: ""

  KenoshaCounty_OpenData:
    CreatedBy: "Kenosha County"
    SiteURL: "https://dataportal.kenoshacounty.org/api/feed/dcat-us/1.1.json"
    SiteName: "KenoshaCounty"
    Spatial: ["Kenosha County", "Wisconsin", "United States"]
    DefaultBbox: "Kenosha"
    SkipList: ""

  MilwaukeeCounty_OpenData:
    CreatedBy: "Milwaukee County"
    SiteURL: "https://data-mclio.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "MilwaukeeCounty"
    DefaultBbox: "MilwaukeeCounty"
    SkipList:
      - UUID: "d7f707071cd24b83ab3b9adb8a7d10ce"
      - UUID: "bce9201dd312445b9b4567ee14d8032a"
      - UUID: "84c7b8d95af04cdda6b0c2ae26590531"
      - UUID: "7a1d3d055d4b4457845c721088c132f0"
    Spatial: ["Milwaukee County", "Wisconsin", "United States"]

  OutagamieCounty_OpenData:
    CreatedBy: "Outagamie County"
    SiteURL: "http://data-ocgis.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "OutagamieCounty"
    Spatial: ["Outagamie County", "Wisconsin", "United States"]
    DefaultBbox: "Outagamie"
    SkipList: ""

  PierceCounty_OpenData:
    CreatedBy: "Pierce County"
    SiteURL: "https://data-piercecounty-wi.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "PierceCounty"
    Spatial: ["Pierce County", "Wisconsin", "United States"]
    DefaultBbox: "Pierce"
    SkipList: ""

  RacineCounty_OpenData:
    CreatedBy: "Racine County"
    SiteURL: "http://data-racinecounty.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "RacineCounty"
    Spatial: ["Racine County", "Wisconsin", "United States"]
    DefaultBbox: "Racine"
    SkipList: ""

  SheboyganCounty_OpenData:
    CreatedBy: "Sheboygan County"
    SiteURL: "https://geospatialhub-shebco.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "SheboyganCounty"
    Spatial: ["Sheboygan County", "Wisconsin", "United States"]
    DefaultBbox: "Sheboygan"
    SkipList: ""

  StCroixCounty_OpenData:
    CreatedBy: "St. Croix County"
    SiteURL: "https://gis-scccdd.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "StCroixCounty"
    Spatial: ["St. Croix County", "Wisconsin", "United States"]
    DefaultBbox: "StCroix"
    SkipList: ""

  SaukCounty_OpenData:
    CreatedBy: "Sauk County"
    SiteURL: "https://data-saukgis.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "SaukCounty"
    Spatial: ["Sauk County", "Wisconsin", "United States"]
    DefaultBbox: "Sauk"
    SkipList: ""

  TrempealeauCounty_OpenData:
    CreatedBy: "Trempealeau County"
    SiteURL: "https://trempealeau-county-information-trempco.hub.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "TrempealeauCounty"
    Spatial: ["Trempealeau County", "Wisconsin", "United States"]
    DefaultBbox: "Trempealeau"
    SkipList:
      - UUID: "afc1effa8b5c4a98a0f35ca54e61d018"

  VilasCounty_OpenData:
    CreatedBy: "Vilas County"
    SiteURL: "https://data-vilas.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "VilasCounty"
    Spatial: ["Vilas County", "Wisconsin", "United States"]
    DefaultBbox: "Vilas"
    SkipList:
      - UUID: "81e69aa1029d41a09b8cdb112f221efe"
      - UUID: "d6e8df34a3034a169073a989123f2086"
      - UUID: "f37edafef8914e8e9d957ac490ed4f23"
      - UUID: "1af79a5fca734020a6a41d954ebdb2e1"
      - UUID: "50d307265f1f435c83b930497339e6d0"
      - UUID: "08a1bcad6ffc4d6eaacbb5382436986a"

  WalworthCounty_OpenData:
    CreatedBy: "Walworth County"
    SiteURL: "https://open-walco.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WalworthCounty"
    Spatial: ["Walworth County", "Wisconsin", "United States"]
    DefaultBbox: "Walworth"
    SkipList: ""

  WashingtonCounty_OpenData:
    CreatedBy: "Washington County"
    SiteURL: "https://gisdata.washcowisco.gov/api/feed/dcat-us/1.1.json"
    SiteName: "WashingtonCounty"
    DefaultBbox: "Washington"
    Spatial: ["Washington County", "Wisconsin", "United States"]
    SkipList:
      - UUID: "6e03e8c26aad4b9c92a87c1063ddb0e3"

  WaukeshaCounty_OpenData:
    CreatedBy: "Waukesha County"
    SiteURL: "http://data-waukeshacounty.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WaukeshaCounty"
    Spatial: ["Waukesha County", "Wisconsin", "United States"]
    DefaultBbox: "Waukesha"
    SkipList: ""

  WaupacaCounty_OpenData:
    CreatedBy: "Waupaca County"
    SiteURL: "https://data2017-04-05t135915451z-waupacacounty.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WaupacaCounty"
    Spatial: ["Waupaca County", "Wisconsin", "United States"]
    DefaultBbox: "Waupaca"
    SkipList: ""

  WausharaCounty_OpenData:
    CreatedBy: "Waushara County"
    SiteURL: "http://data-waushara.opendata.arcgis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WausharaCounty"
    Spatial: ["Waushara County", "Wisconsin", "United States"]
    DefaultBbox: "Waushara"
    SkipList: ""

  WoodCounty_OpenData:
    CreatedBy: "Wood County"
    SiteURL: "https://opendata.woodcogis.com/api/feed/dcat-us/1.1.json"
    SiteName: "WoodCounty"
    Spatial: ["Wood County", "Wisconsin", "United States"]
    DefaultBbox: "Wood"
    AppList:
      - UUID: "623300abe751422091003f2ba5f4b2e9"
      - UUID: "dbda3bb2984345f08d1b4de4523031df"
      - UUID: "ee70f8224c9e47bdb816a4979ca092c4"
      - UUID: "61dd328dbae5414ca2c2ee46091c7e12"
      - UUID: "3bf1d03d96d1403588f2f758374cbb2a"
    SkipList: ""
