{
    "@type": "dcat:Dataset",
    "identifier": "https://www.arcgis.com/home/item.html?id=11f112f50f6a4bbfb0b415ae54193c7e&sublayer=0",
    "landingPage": "https://gis-mclio.opendata.arcgis.com/maps/MCLIO::general-land-use-2010-1",
    "title": "General Land Use 2010",
    "description": "",
    "keyword": ["land use"],
    "issued": "2023-12-19T21:26:35.000Z",
    "modified": "2023-12-19T21:26:36.000Z",
    "publisher": {"name": "Milwaukee County GIS & Land Information"},
    "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "GISBridgetMonahan",
        "hasEmail": "mailto:mclioservices@milwaukeecountywi.gov",
    },
    "accessLevel": "public",
    "spatial": "-88.0744,42.8434,-87.8152,43.1906",
    "license": "",
    "distribution": [
        {
            "@type": "dcat:Distribution",
            "title": "ArcGIS Hub Dataset",
            "format": "Web Page",
            "mediaType": "text/html",
            "accessURL": "https://gis-mclio.opendata.arcgis.com/maps/MCLIO::general-land-use-2010-1",
        },
        {
            "@type": "dcat:Distribution",
            "title": "ArcGIS GeoService",
            "format": "ArcGIS GeoServices REST API",
            "mediaType": "application/json",
            "accessURL": "https://lio.milwaukeecountywi.gov/arcgis/rest/services/Environmental/Environmental/FeatureServer/0",
        },
        {
            "@type": "dcat:Distribution",
            "title": "CSV",
            "format": "CSV",
            "mediaType": "text/csv",
            "accessURL": "https://gis-mclio.opendata.arcgis.com/api/download/v1/items/11f112f50f6a4bbfb0b415ae54193c7e/csv?layers=0",
        },
        {
            "@type": "dcat:Distribution",
            "title": "GeoJSON",
            "format": "GeoJSON",
            "mediaType": "application/vnd.geo+json",
            "accessURL": "https://gis-mclio.opendata.arcgis.com/api/download/v1/items/11f112f50f6a4bbfb0b415ae54193c7e/geojson?layers=0",
        },
        {
            "@type": "dcat:Distribution",
            "title": "Shapefile",
            "format": "ZIP",
            "mediaType": "application/zip",
            "accessURL": "https://gis-mclio.opendata.arcgis.com/api/download/v1/items/11f112f50f6a4bbfb0b415ae54193c7e/shapefile?layers=0",
        },
        {
            "@type": "dcat:Distribution",
            "title": "KML",
            "format": "KML",
            "mediaType": "application/vnd.google-earth.kml+xml",
            "accessURL": "https://gis-mclio.opendata.arcgis.com/api/download/v1/items/11f112f50f6a4bbfb0b415ae54193c7e/kml?layers=0",
        },
    ],
    "theme": ["geospatial"],
}
